### PR TITLE
Minor cleanup, remove some cruft

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by samip5** [comment]
Umm, the includejson parser is used?

**Review by samip5 — CHANGES_REQUESTED** [review]
parsers/include/includejson is used by build.sh.

**Comment by jonesmz** [comment]
> parsers/include/includejson is used by build.sh.

$PARSERS/includejson/includejson ${PROJECT}.json is used by build.sh
Slight difference, duplicated files with almost no differences.

**Comment by samip5** [comment]
> > parsers/include/includejson is used by build.sh.
> 
> $PARSERS/includejson/includejson ${PROJECT}.json is used by build.sh
> Slight difference, duplicated files with almost no differences.

To me that looks like it's still the removed file or am I missing something?

**Review by samip5 — APPROVED** [review]

**Pull request merged**
