### PR TITLE
Use the F flag for binfmt so that the host qemu instance is used

### PR DESCRIPTION
**Pull request by jonesmz**
for aarch64 and arm binaries, and not an instance inside the chroot

### CODE REVIEW

**Comment by jonesmz** [comment]
This also alleviates the need for the qemu binary to be statically linked, i believe.

**Review by samip5 — COMMENTED** [review]
I'm not sure about how this actually would work, so I'm not going to approve it.
If the host does NOT have qemu installed, what's the error it throws out?
The error should be catched.

**Review by samip5 — COMMENTED** [review]
I'm not sure about how this actually would work, so I'm not going to approve it.
If the host does NOT have qemu installed, what's the error it throws out?
The error should be catched.

**Comment by jonesmz** [comment]
> I'm not sure about how this actually would work, so I'm not going to approve it. If the host does NOT have qemu installed, what's the error it throws out? The error should be catched.

Same error you get if the host doesn't have the qemu binary without the F flag. "File not found".

The point of the F flag is that it "pre-loads" the qemu binary used for evaluating non-native code, instead of loading the binary on a per executable basis. This allows for non staticly linked qemu binaries to be used, and removes the need to have the qemu binary copied into the chroot.

**Comment by samip5** [comment]
Please rebase on the current master.

**Review by samip5 — APPROVED** [review]
I know that this might break something else, but we shall fix when we see something like that.

**Pull request merged**
